### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ASDWQad** [phith0n/arbitrary-php-extension#1]
/root/arbitrary-php-extension/arbitraryphp/ext/arbitraryphp.h:7:35: 致命错误：arbitraryphp/main.zep.h：没有那个文件或目录
 #include "arbitraryphp/main.zep.h"
                                   ^

**Comment by phith0n** [comment]
错误发生在什么哪个阶段，你的具体操作过程，详细漏洞信息。

**Comment by ASDWQad** [comment]
安装写的太简单了，没看懂，下载到源码包后运行了下build-ext.sh 报错
+ BASEDIR=/app
+ cd /app/arbitraryphp
build-ext.sh: 第 8 行:cd: /app/arbitraryphp: 没有那个文件或目录
然后我把app 改成了./ ok了，然后我没有安装zephir  又报错了。
-------------
切换到arbitraryphp/ext目录手动安装扩展
./configure --with-php-config=/usr/local/php/bin/php-config
make报错

In file included from /root/arbitrary-php-extension-1.0.0/arbitraryphp/ext/arbitraryphp.c:16:0:
/root/arbitrary-php-extension-1.0.0/arbitraryphp/ext/arbitraryphp.h:7:35: 致命错误：arbitraryphp/main.zep.h：没有那个文件或目录
 #include "arbitraryphp/main.zep.h"
                                   ^
编译中断。
make: *** [arbitraryphp.lo] 错误 1

**Comment by phith0n** [comment]
如果是安装的话，直接下载编译好的so文件即可：https://github.com/phith0n/arbitrary-php-extension/releases

自行编译的话需要使用[zephir](https://github.com/phalcon/zephir)，具体步骤参考其文档。
否则请使用docker，文档里写了方法，build-ext.sh是docker容器内使用的脚本，直接运行将会出错。
自行编译需要对PHP底层与扩展开发有一定了解，这个暂时只能这样。
